default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: orchestra_ai_development
  host: localhost
  port: 5432
  username: ubuntu
  password: postgres
  schema_search_path: public
  min_messages: notice

test:
  <<: *default
  database: orchestra_ai_test

production:
  primary: &primary_production
    <<: *default
    database: orchestra_ai_production
    username: orchestra_ai
    password: <%= ENV["ORCHESTRA_AI_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: orchestra_ai_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: orchestra_ai_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: orchestra_ai_production_cable
    migrations_paths: db/cable_migrate
